name: Built ImmortalWrt-v23.05-R4AGv2-1

on:
  workflow_dispatch:

env:
  VERSION: 23.05.1

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Image Builder Prerequisites
      run: |
        sudo apt-get update
        sudo apt install build-essential clang flex bison g++ gawk \
        gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
        python3-distutils rsync unzip zlib1g-dev file wget tree
    - name: Build
      run: |
        curl -LO https://downloads.immortalwrt.org/releases/${VERSION}/targets/ramips/mt7621/immortalwrt-imagebuilder-${VERSION}-ramips-mt7621.Linux-x86_64.tar.xz
        tar xf immortalwrt-imagebuilder-${VERSION}-ramips-mt7621.Linux-x86_64.tar.xz
        cd immortalwrt-imagebuilder-${VERSION}-ramips-mt7621.Linux-x86_64
        echo "src/gz immortalwrt_custom https://op.dllkids.xyz/packages/mipsel_24kc" >> repositories.conf
        make image \
        PROFILE="xiaomi_mi-router-4a-gigabit-v2" \
        PACKAGES="luci-theme-argon luci-app-argon-config luci-app-ssr-plus" \
        FILES="files"
        tree ./bin
