name: Built ImmortalWrt-v23.05-R4AGv2-1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Image Builder Prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk \
        gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
        python3-distutils rsync unzip zlib1g-dev file wget tree
    - name: Build
      run: |
        git clone -b openwrt-23.05 --single-branch --filter=blob:none https://github.com/immortalwrt/immortalwrt
        cd immortalwrt
        echo 'src-git kenzo https://github.com/kenzok8/openwrt-packages' >> feeds.conf.default
        echo 'src-git small https://github.com/kenzok8/small' >> feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        curl -Lo /tmp/offical-config https://downloads.immortalwrt.org/releases/23.05.1/targets/ramips/mt7621/config.buildinfo
        grep -Ev 'CONFIG_TARGET_DEVICE|CONFIG_TARGET_MULTI_PROFILE' /tmp/offical-config > .config
        sed -i '/CONFIG_TARGET_ramips_mt7621/aCONFIG_TARGET_ramips_mt7621_DEVICE_xiaomi_mi-router-4a-gigabit-v2=y' .config
        sed -i '/CONFIG_PACKAGE_zlib/aCONFIG_PACKAGE_luci-app-ssr-plus=y' .config
        sed -i '/CONFIG_ALL_KMODS=y/d' .config
        sed -i '/CONFIG_ALL_NONSHARED=y/d' .config
        sed -i '$aCONFIG_IPADDR="192.168.31.1"'
        echo "Preview Offical Config"
        grep -Ev '^#|^$' .config
        make -j$(nproc) defconfig
        echo "Preview Result Config"
        grep -Ev '^#|^$' .config
        make -j$(nproc) download clean world
        tree ./bin
